apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacatalogservice
  template:
    metadata:
      labels:
        app: datacatalogservice
    spec:
      containers:
      - name: datacatalogservice
        image: prakashkmr/datacatalogservice:latest  

---

apiVersion: v1
kind: Service
metadata:
  name: datacatalog-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: datacatalogservice
  ports:
  - name: datacatalogservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: datacatalogservice-grpc
    protocol: TCP
    port: 666
    targetPort: 666  
    



